# Generated by Django 4.1.6 on 2023-02-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='soft_drinks',
            new_name='soft_drink',
        ),
    ]
