# Generated by Django 4.1.6 on 2023-02-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0002_rename_soft_drinks_soft_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='alcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
